spring.ai.bedrock.titan.embedding.input-type=text

embabel.models.default-llm=us.amazon.nova-pro-v1:0
embabel.models.llms.best=us.amazon.nova-pro-v1:0
embabel.models.llms.balanced=us.amazon.nova-lite-v1:0
embabel.models.default-embedding-model=amazon.titan-embed-text-v2:0
