CREATE TABLE IF NOT EXISTS "contact" (
   "ID" BIGINT AUTO_INCREMENT PRIMARY KEY,
   "name" VARCHAR(255) NOT NULL,
   "email" VARCHAR(255),
   "writeup" TEXT,
   "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
